In [1]:
import numpy as np

#Примеры создания массивов

Из обычных списков

In [3]:
list_array = np.array([1, 2, 3]) # Одномерный массив
list_array

array([1, 2, 3])

In [4]:
list_array = np.array([[1, 2, 3], [4, 5, 6]]) # Двумерный массив
list_array

array([[1, 2, 3],
       [4, 5, 6]])

С использованием zeros

In [6]:
zeros_array = np.zeros(5) # Одномерный массив из пяти нулей
zeros_array

array([0., 0., 0., 0., 0.])

In [7]:
zeros_array = np.zeros((2, 3)) # Двумерный массив из нулей формы 2 на 3
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.]])

С использованием ones

In [8]:
ones_array = np.ones(5) # Одномерный массив из пяти единиц
ones_array

array([1., 1., 1., 1., 1.])

In [9]:
ones_array = np.ones((3, 5)) # Двумерный массив из нулей формы 3 на 5
ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

С использованием arange

In [12]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [13]:
arr = np.arange(2, 8) # С началом и концом
arr

[2 3 4 5 6 7]


In [15]:
arr = np.arange(0, 10, 2) # С шагом
arr

array([0, 2, 4, 6, 8])

# Демонстрация атрибутов

In [16]:
ones_array.shape # Форма

(3, 5)

In [17]:
ones_array.dtype # тип данных

dtype('float64')

In [18]:
ones_array = np.ones((3, 5), dtype=int) # как создавался бы массив, если бы нм были нужны целые числа
ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Индексирование и срезы

In [19]:
arr #Весь массив

array([0, 2, 4, 6, 8])

In [20]:
arr[1] #Второй элемент

np.int64(2)

In [22]:
arr[-1] #Последний элемент

np.int64(8)

In [23]:
arr[1:-1] #Все элементы кроме первого и последнего

array([2, 4, 6])

In [25]:
arr[::2] #Только элементы на нечётных позициях

array([0, 4, 8])

In [26]:
arr[1::2] #Только элементы на чётных позициях

array([2, 6])

# Операции с массивом

In [35]:
#Поэлементое сложение
np.arange(1, 7) + np.arange(-1, -7, -1)

array([0, 0, 0, 0, 0, 0])

In [36]:
#Поэлементое умножение
np.arange(1, 7) * np.arange(-1, -7, -1)

array([ -1,  -4,  -9, -16, -25, -36])

In [37]:
# Поэлементное умножение двумерного массива

np.array([[1, 2], [3, 4]]) * np.array([[2, 2], [2, 2]])

array([[2, 4],
       [6, 8]])

In [38]:
# Матричное умножение

np.array([[1, 2], [3, 4]]) @ np.array([[2, 2], [2, 2]])

array([[ 6,  6],
       [14, 14]])

# Простая статистика

In [31]:
arr = np.random.randn(100000) # 100000 значений из стандартного нормального распределения (мат ожидание 0, стандартное отклонение 1)
arr[:100] # Первые 100

array([ 0.96790216,  0.14574464,  1.68981347, -1.52147297, -0.41864645,
        0.44661517, -0.11299204,  1.87520909,  0.43709814, -0.73801917,
        0.21008589, -1.81308127,  0.86587221,  0.13534789, -1.4485147 ,
        1.21102531, -0.94826313, -0.33591329,  0.31030347, -0.34750968,
        1.43121059, -0.1760363 ,  0.37616642,  0.64753376,  0.38593578,
       -2.55203494,  0.18582539,  2.25754318,  2.09115975, -1.01895085,
        0.5353172 , -0.74253785, -1.02376187, -0.20315077,  0.07057018,
       -2.33463713, -0.92670178,  1.32108802, -1.28505037, -0.66724275,
        0.86068352,  1.08463056, -1.11940324, -0.92047254,  0.35686843,
        2.13220285, -0.81593154, -0.82833061, -1.72996494, -0.61787329,
        1.1527089 ,  1.48197855,  0.84403495, -0.31765349, -0.28284762,
       -1.47895485, -0.70848568,  1.12810022,  0.35456968,  0.83286705,
        1.06925022,  0.36823169, -1.26205535,  1.02894569, -0.8757888 ,
       -1.50850898,  0.11334346,  1.07653848,  0.71431102,  1.59

In [32]:
arr.mean() # Среднее значение

np.float64(0.0005492397294334938)

In [34]:
arr.std() # Стандартное отклонение

np.float64(0.9972200001821064)